name: Compile ESPHome Binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Fix for the 2026 Node runner warning
      - name: Configure Node24 Environment
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      # Use the official isolated ESPHome compiler container to bypass all host server bugs
      - name: Compile ESPHome Firmware
        uses: esphome/build-action@v3.2.0
        with:
          yaml_file: jnge-mppt.yaml

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-mppt-firmware
          path: |
            .esphome/build/**/*.bin
          if-no-files-found: error
